name: flutter_restaurant
description: Restaurant App
version: 0.0.1+1
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  animations: ^2.0.7
  auto_route: ^5.0.4
  bloc: ^8.1.0
  cached_network_image: ^3.2.3
  dartz: ^0.10.1
  equatable: ^2.0.5
  firebase_auth: ^4.1.5
  firebase_core: ^2.3.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.2.16
  flutter_polyline_points: ^1.0.0
  form_field_validator: ^1.1.0
  geolocator: ^9.0.2
  geolocator_linux: ^0.1.2
  get_it: ^7.2.0
  google_fonts: ^3.0.1
  http: ^0.13.5
  hydrated_bloc: ^9.0.0
  infinite_scroll_pagination: ^3.2.0
  injectable: ^2.1.0
  intl: ^0.17.0
  kt_dart: ^1.0.0
  material_design_icons_flutter: ^6.0.7096
  path_provider: ^2.0.11
  pretty_qr_code: ^2.0.2
  syncfusion_flutter_maps: ^20.3.59
  timeago: ^3.3.0
  wakelock: ^0.6.2

dev_dependencies:
  auto_route_generator: ^5.0.3
  build_runner: ^2.3.2
  flutter_test:
    sdk: flutter
  icons_launcher: ^2.0.6
  injectable_generator: ^2.1.2
  lint: ^2.0.1

# flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: '#00FFFF'
  color_dark: '#1E1E1E'
  image: 'assets/images/app-logo.png'

## flutter pub run icons_launcher:create
flutter_icons:
  image_path: 'assets/images/app-logo.png'
  adaptive_icon_background: '#76517b'
  adaptive_icon_foreground: 'assets/images/app-logo-adaptive.png'
  ios: true
  android: true
  windows: true
  linux: true
  web: true
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  generate: true
