name: flutter_restaurant
description: Restaurant App
version: 0.0.1+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  auto_route: ^4.0.0
  bloc: ^8.0.3
  cloud_firestore: ^3.1.14
  equatable: ^2.0.3
  firebase_auth: ^3.3.17
  firebase_core: ^1.16.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.1.6
  flutterfire_ui: ^0.4.0+5
  geolocator: ^8.2.1
  get_it: ^7.2.0
  google_fonts: ^2.3.2
  google_maps_flutter: ^2.1.5
  hydrated_bloc: ^8.1.0
  injectable: ^1.5.3
  intl: ^0.17.0
  material_design_icons_flutter: ^5.0.6595
  package_info_plus: ^1.4.2
  path_provider: ^2.0.10

dev_dependencies:
  auto_route_generator: ^4.0.0
  build_runner: ^2.1.10
  flutter_test:
    sdk: flutter
  injectable_generator: ^1.5.3
  lint: ^1.8.2

flutter_native_splash:
  color: "#00FFFF"
  color_dark: "#1E1E1E"
  image: "assets/images/restaurant-logo.png"

assets:
  - assets/images/

flutter:
  uses-material-design: true
  generate: true
