// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBC1ogdklGgz86CdT6ylaOW4obelcFt7qc',
    appId: '1:604627191517:web:fb481d0aee9a9b5d307d34',
    messagingSenderId: '604627191517',
    projectId: 'restaurant-70076',
    authDomain: 'restaurant-70076.firebaseapp.com',
    storageBucket: 'restaurant-70076.appspot.com',
    measurementId: 'G-ZXJPESWE2Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfIQFNju-sqE_z_Llq9UcmMjpUnBc2U8Y',
    appId: '1:604627191517:android:b55dfc0598129c1a307d34',
    messagingSenderId: '604627191517',
    projectId: 'restaurant-70076',
    storageBucket: 'restaurant-70076.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcSknQPOdEM-PKlhYTJ4aJsUia4PXRMgg',
    appId: '1:604627191517:ios:9723c0d56038e745307d34',
    messagingSenderId: '604627191517',
    projectId: 'restaurant-70076',
    storageBucket: 'restaurant-70076.appspot.com',
    androidClientId:
        '604627191517-30av0r43v5ivgm1627ocert4fno5711e.apps.googleusercontent.com',
    iosClientId:
        '604627191517-b2sq4ie2jrej0jgoih6ioep9vrbigk6v.apps.googleusercontent.com',
    iosBundleId: 'com.azlir.restaurant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBC1ogdklGgz86CdT6ylaOW4obelcFt7qc',
    appId: '1:604627191517:web:5dc6648af62d8555307d34',
    messagingSenderId: '604627191517',
    projectId: 'restaurant-70076',
    authDomain: 'restaurant-70076.firebaseapp.com',
    storageBucket: 'restaurant-70076.appspot.com',
    measurementId: 'G-5LZXDZZPVP',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyBC1ogdklGgz86CdT6ylaOW4obelcFt7qc',
    appId: '1:604627191517:web:c493445fc0892a11307d34',
    messagingSenderId: '604627191517',
    projectId: 'restaurant-70076',
    authDomain: 'restaurant-70076.firebaseapp.com',
    storageBucket: 'restaurant-70076.appspot.com',
    measurementId: 'G-8LNVQTVZFS',
  );
}
